# Generated by Django 4.0.4 on 2022-05-02 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='placeholder_name',
        ),
    ]
