# Generated by Django 4.0.4 on 2022-05-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_payment_placeholder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='placeholder_name',
            field=models.CharField(max_length=0, null=True),
        ),
    ]
