# Generated by Django 4.0.4 on 2022-05-02 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_payment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30, null=True)),
                ('price', models.CharField(max_length=30)),
                ('is_available', models.BooleanField(default=True, null=True)),
                ('title', models.CharField(max_length=30)),
                ('reserved_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.user')),
            ],
        ),
    ]
