# Generated by Django 4.0.4 on 2022-05-02 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_insurancedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InsuranceData',
        ),
    ]
