# Generated by Django 4.0.4 on 2022-05-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_insurancedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancedata',
            name='title',
            field=models.CharField(max_length=666),
        ),
    ]
