# Generated by Django 4.0.4 on 2022-05-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_insurancedata_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancedata',
            name='country',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
