# Generated by Django 4.0.4 on 2022-05-11 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_candidate_recruiter_vacancy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateTimeField()),
                ('to', models.DateTimeField()),
                ('general_description', models.CharField(max_length=200, null=True)),
                ('responsibilities', models.CharField(max_length=200, null=True)),
                ('technologies_used', models.JSONField(verbose_name=[])),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.candidate')),
            ],
        ),
        migrations.DeleteModel(
            name='InsuranceData',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='service.recruiter'),
        ),
    ]
