# Generated by Django 4.0.4 on 2022-05-12 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_experience_delete_insurancedata_delete_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='candidate',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='service.candidate'),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=80)),
                ('time', models.DateTimeField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_interviews', to='service.candidate')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_interviews', to='service.interviewer')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_interviews', to='service.recruiter')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.vacancy')),
            ],
        ),
    ]
