# Generated by Django 4.0.4 on 2022-05-12 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_interviewer_alter_candidate_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='email',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='name',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='phone_number',
        ),
    ]
