# Generated by Django 4.0.4 on 2022-05-12 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_remove_interview_email_remove_interview_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='time of interview')),
                ('percentage_of_correct_questions', models.SmallIntegerField(verbose_name='percentage of correct questions')),
                ('overall_estimation', models.SmallIntegerField(verbose_name='overall estimation')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_results', to='service.candidate')),
            ],
        ),
    ]
