# Generated by Django 4.0.4 on 2022-05-12 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_interviewresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresult',
            name='vacancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.vacancy'),
        ),
    ]
