# Generated by Django 4.0.4 on 2022-05-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_alter_interviewresult_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
