# Generated by Django 4.0.4 on 2022-05-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_remove_candidate_skills_delete_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='recruiter',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.CharField(max_length=200),
        ),
    ]
